#!/bin/bash

ip link set dev eth0 up
ip address add 192.168.172.129/25 dev eth0
ip link set dev eth1 up
ip address add 200.4.253.1/26 dev eth1
echo 1 >/proc/sys/net/ipv4/ip_forward
ip route add 0.0.0.0/0 via 200.4.253.2

service isc-dhcp-server start 


iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

# Enlever les autorisations
iptables -P FORWARD DROP

# Autoriser toutes requêtes du réseaux local
iptables -A FORWARD -s 192.168.172.128/25 -j ACCEPT

#Autoriser les pings
iptables -A FORWARD -p icmp -j ACCEPT

# Autoriser les trames HTTP
iptables -A FORWARD -i eth1 -s 200.4.253.196 -p tcp --sport 80 -j ACCEPT

# Autoriser les trames DNS
iptables -A FORWARD -i eth1 -s 200.4.253.194 -p udp --sport 53 -j ACCEPT

# Autoriser les trames FTP
iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 1024:65535 -j ACCEPT

#iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 1024:65535 --dport 1024:65535 -j ACCEPT
#iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 23 -j ACCEPT
#iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 80 -j ACCEPT
#iptables -A FORWARD -i eth1 -s 200.4.253.195 -p tcp --sport 20 -j ACCEPT
